### ISSUE TITLE
Add metadata categories to inis

### ISSUE THREAD

**Issue by bambooforest** [acqdiv/acqdiv#12]
@Jancso - I think I'll add a couple metadata categories to the corpora table:

- License (is the corpus private or CC)
- InputFormat (CHAT, Toolbox)

And maybe some information on the language's genealogical and geographic location. That way we can easily dump the information into tables for publications.

What do you think?

**Comment by Jancso** [comment]
Sounds good.

I'm just working on merging the inis. I just pushed the changes, but I'm not finished yet with all the testing. Everything is now in one global config file called 'config.ini'. Unfortunately, I deleted the input format info because I thought we wouldn't need it...So, you have to add it back.
